_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

sproyect_tarea:
    resource: "@SproyectTareaBundle/Resources/config/routing.yml"
    prefix:   /

crud_persona:
    resource: "@CrudPersonaBundle/Resources/config/routing.yml"
    prefix:   /crud

m7_editor:
    resource: "@M7EditorBundle/Resources/config/routing.yml"
    prefix:   /m7